# Extract Missing Statistics form Manuscript (FINAL)
# ==========================================
# Author: Generated for manuscript completion
# Date: 2026-01-05
#
# INPUT: 'rsf_gain_predictions_for_r.csv'
# (This file is generated by the updated survival_models.py script)

library(survival)
library(dplyr)

print("Starting extraction of missing statistics from clean RSF-GAIN data...")

# Check for any matching files
files <- list.files(pattern = "rsf_gain_predictions_.*\\.csv")

if (length(files) == 0) {
    stop("Error: No 'rsf_gain_predictions_*.csv' files found.\nPlease run the updated 'survival_models.py' first.")
}

# Prefer 'real', 'full', or 'original' if exists
chosen_file <- files[1]
if (any(grepl("real|full|original", files, ignore.case = TRUE))) {
    # Pick the first match for any of these keywords
    chosen_file <- files[grep("real|full|original", files, ignore.case = TRUE)[1]]
}

print(paste("Using file:", chosen_file))
data <- read.csv(chosen_file)
print(paste("Loaded", nrow(data), "rows."))

# ============================================================================
# 1. CALIBRATION RANGES
# ============================================================================
print("1. CALCULATING CALIBRATION RANGES")

data$risk_decile <- cut(data$Predicted_Risk,
    breaks = quantile(data$Predicted_Risk, probs = seq(0, 1, 0.1)),
    labels = FALSE, include.lowest = TRUE
)

calib <- data %>%
    group_by(risk_decile) %>%
    summarise(
        mean_predicted_risk = mean(Predicted_Risk),
        observed_event_rate = mean(Observed_Status)
    )

# Save calibration results
write.csv(calib, "calibration_results.csv", row.names = FALSE)
print("Saved: calibration_results.csv")

print(sprintf("Predicted Risk: %.4f - %.4f", min(calib$mean_predicted_risk), max(calib$mean_predicted_risk)))
print(sprintf("Observed Rate: %.4f - %.4f", min(calib$observed_event_rate), max(calib$observed_event_rate)))

# ============================================================================
# 2. SURVIVAL PROBABILITIES (30 & 60 DAYS)
# ============================================================================
print("2. CALCULATING SURVIVAL PROBABILITIES")

# Fit KM by Risk Group
km_fit <- survfit(Surv(Observed_Time, Observed_Status) ~ Risk_Group, data = data)

results_surv <- data.frame()

for (group in levels(as.factor(data$Risk_Group))) {
    sub <- data[data$Risk_Group == group, ]
    fit <- survfit(Surv(Observed_Time, Observed_Status) ~ 1, data = sub)
    summ <- summary(fit, times = c(30, 60), extend = TRUE)

    # Check bounds
    s30 <- if (length(summ$surv) >= 1) summ$surv[1] else NA
    l30 <- if (length(summ$lower) >= 1) summ$lower[1] else NA
    u30 <- if (length(summ$upper) >= 1) summ$upper[1] else NA

    s60 <- if (length(summ$surv) >= 2) summ$surv[2] else NA
    l60 <- if (length(summ$lower) >= 2) summ$lower[2] else NA
    u60 <- if (length(summ$upper) >= 2) summ$upper[2] else NA

    row <- data.frame(
        Group = group,
        Surv_30 = s30, CI_30_Lower = l30, CI_30_Upper = u30,
        Surv_60 = s60, CI_60_Lower = l60, CI_60_Upper = u60
    )
    results_surv <- rbind(results_surv, row)
}

write.csv(results_surv, "survival_probabilities.csv", row.names = FALSE)
print("Saved: survival_probabilities.csv")
print(results_surv)

# ============================================================================
# 3. HAZARD RATIO
# ============================================================================
print("3. CALCULATING HAZARD RATIO")

# Create High Risk binary (1/0)
data$is_high_risk <- ifelse(data$Risk_Group == "High", 1, 0)

cox_fit <- coxph(Surv(Observed_Time, Observed_Status) ~ is_high_risk, data = data)
hr <- exp(coef(cox_fit))
ci <- exp(confint(cox_fit))
p <- summary(cox_fit)$coefficients[, "Pr(>|z|)"]

hr_result <- data.frame(
    HR = hr,
    CI_Lower = ci[1],
    CI_Upper = ci[2],
    P_Value = p
)

write.csv(hr_result, "hazard_ratio.csv", row.names = FALSE)
print("Saved: hazard_ratio.csv")
print(hr_result)

print("DONE. All results saved to CSV files.")
